#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/techno-tim/littlelink-server
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [littlelink-server documentation](https://github.com/techno-tim/littlelink-server).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  META_TITLE: Harry Westerman
  META_DESCRIPTION: Harry Westerman Link page
  META_AUTHOR: Harry Westerman
  THEME: Dark
  FAVICON_URL: https://pbs.twimg.com/profile_images/1286144221217316864/qIAsKOpB_200x200.jpg
  AVATAR_URL: https://pbs.twimg.com/profile_images/1528564313/Harm_Wiecher_Westerman_2011_400x400.jpg
  AVATAR_2X_URL: https://pbs.twimg.com/profile_images/1528564313/Harm_Wiecher_Westerman_2011_400x400.jpg
  AVATAR_ALT: Harry Westerman Profile Pic
  NAME: HarryWesterman
  BIO: Hey! Just a place where you can connect with me!
  GITHUB: https://github.com/harrywesterman
  TWITTER: https://twitter.com/harrywesterman
  INSTAGRAM: https://www.instagram.com/harrywesterman/
  YOUTUBE: https://www.youtube.com/channel/UCaX3uOdKN-UaEG1BcoLQarg
  TWITCH: https://www.twitch.tv/harrywesterman
  DISCORD: https://discord.gg/eSrGGHgp
  TIKTOK: https://www.tiktok.com/@harrywesterman08
  # KIT: https://kit.co/TechnoTim
  FACEBOOK: https://www.facebook.com/Harrywestermanede
  # FACEBOOK_MESSENGER: https://facebook.com
  LINKED_IN: https://www.linkedin.com/in/harry-westerman/
  # PRODUCT_HUNT: https://www.producthunt.com/
  # SNAPCHAT: https://www.snapchat.com/
  # SPOTIFY: https://www.spotify.com/
  # REDDIT: https://www.reddit.com/
  # MEDIUM: https://medium.com
  # PINTEREST: https://www.pinterest.com/
  EMAIL: harrywesterman@gmail.com
  # EMAIL_ALT: you@example.com
  # SOUND_CLOUD: https://souncloud.com
  # FIGMA: https://figma.com
  # TELEGRAM: https://telegram.org/
  # TUMBLR: https://www.tumblr.com/
  # STEAM: https://steamcommunity.com/
  # VIMEO: https://vimeo.com/
  # WORDPRESS: https://wordpress.com/
  # GOODREADS: https://www.goodreads.com/
  # SKOOB: https://www.skoob.com.br/
  FOOTER: Thanks for stopping by!

#  -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000
        
ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
